
import javax.swing.JOptionPane;


public class InterfazCompra extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazCompra.class.getName());

    /**
     * Creates new form InterfazCompra
     */
    public InterfazCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDetallesVuelo = new javax.swing.JPanel();
        TxtTituloDetalles = new javax.swing.JLabel();
        TxtTituloDetalles1 = new javax.swing.JLabel();
        TxtTituloDetalles2 = new javax.swing.JLabel();
        TxtTituloDetalles3 = new javax.swing.JLabel();
        TxtNumPersonas = new javax.swing.JTextField();
        BtnMaletas = new javax.swing.JToggleButton();
        BtnVueloRegreso = new javax.swing.JToggleButton();
        BtnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelDetallesVuelo.setBackground(new java.awt.Color(102, 204, 255));

        TxtTituloDetalles.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        TxtTituloDetalles.setText("DETALLES DEL VUELO");

        TxtTituloDetalles1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        TxtTituloDetalles1.setText("VUELO DE REGRESO");

        TxtTituloDetalles2.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        TxtTituloDetalles2.setText("¿TIENE MALETAS?");

        TxtTituloDetalles3.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        TxtTituloDetalles3.setText("NUMERO DE PERSONAS");

        TxtNumPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumPersonasActionPerformed(evt);
            }
        });

        BtnMaletas.setText("NO");
        BtnMaletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMaletasActionPerformed(evt);
            }
        });

        BtnVueloRegreso.setText("NO");
        BtnVueloRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVueloRegresoActionPerformed(evt);
            }
        });

        BtnSiguiente.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.setActionCommand("Siguiente");
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDetallesVueloLayout = new javax.swing.GroupLayout(PanelDetallesVuelo);
        PanelDetallesVuelo.setLayout(PanelDetallesVueloLayout);
        PanelDetallesVueloLayout.setHorizontalGroup(
            PanelDetallesVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetallesVueloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDetallesVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetallesVueloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelDetallesVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetallesVueloLayout.createSequentialGroup()
                                .addComponent(TxtTituloDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetallesVueloLayout.createSequentialGroup()
                                .addComponent(BtnMaletas)
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetallesVueloLayout.createSequentialGroup()
                                .addComponent(TxtNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetallesVueloLayout.createSequentialGroup()
                        .addComponent(TxtTituloDetalles1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(BtnVueloRegreso)
                        .addGap(101, 101, 101))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetallesVueloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelDetallesVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDetallesVueloLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(TxtTituloDetalles2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
            .addGroup(PanelDetallesVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDetallesVueloLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(TxtTituloDetalles3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );
        PanelDetallesVueloLayout.setVerticalGroup(
            PanelDetallesVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetallesVueloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtTituloDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(BtnMaletas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(TxtNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(PanelDetallesVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTituloDetalles1)
                    .addComponent(BtnVueloRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(BtnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelDetallesVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDetallesVueloLayout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(TxtTituloDetalles2)
                    .addContainerGap(333, Short.MAX_VALUE)))
            .addGroup(PanelDetallesVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDetallesVueloLayout.createSequentialGroup()
                    .addGap(205, 205, 205)
                    .addComponent(TxtTituloDetalles3)
                    .addContainerGap(227, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDetallesVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDetallesVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMaletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMaletasActionPerformed
    if (BtnMaletas.isSelected()) {
        BtnMaletas.setText("SI");
    } else {
        BtnMaletas.setText("NO");
    }
    }//GEN-LAST:event_BtnMaletasActionPerformed

    private void BtnVueloRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVueloRegresoActionPerformed
       if (BtnVueloRegreso.isSelected()) {
        BtnVueloRegreso.setText("SI");
    } else {
        BtnVueloRegreso.setText("NO");
    }
    }//GEN-LAST:event_BtnVueloRegresoActionPerformed

    private void TxtNumPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumPersonasActionPerformed
        
        

    }//GEN-LAST:event_TxtNumPersonasActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
            
        DatosDePasajeros dp = new DatosDePasajeros();
        
        try {
    int numPersonas = Integer.parseInt(TxtNumPersonas.getText());

    if (numPersonas <= 0) {
        JOptionPane.showMessageDialog(null,
            "El número de personas no es posible");
    }
    else{
    dp.setVisible(true);
    setVisible(false);
    }

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null,
        "Solo se permiten números enteros");
}

    }//GEN-LAST:event_BtnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazCompra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton BtnMaletas;
    private javax.swing.JButton BtnSiguiente;
    public javax.swing.JToggleButton BtnVueloRegreso;
    private javax.swing.JPanel PanelDetallesVuelo;
    private javax.swing.JTextField TxtNumPersonas;
    private javax.swing.JLabel TxtTituloDetalles;
    private javax.swing.JLabel TxtTituloDetalles1;
    private javax.swing.JLabel TxtTituloDetalles2;
    private javax.swing.JLabel TxtTituloDetalles3;
    // End of variables declaration//GEN-END:variables
}
